### PR TITLE
CP-1003 update license, catcher

### PR DESCRIPTION
**Pull request by trentgrover-wf**
## Issue
- update license text

## Changes
**Source:**
- docs only

**Tests:**
- none

## Areas of Regression
- none

## Testing
- none

## Code Review
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf 
@jayudey-wf

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
Is this pr still desired? @trentgrover-wf

**Comment by maxwellpeterson-wf** [comment]
Guessing this repo can be deleted.

**Comment by trentgrover-wf** [comment]
@jayudey-wf might as well merge this - docs only change

**Comment by jayudey-wf** [comment]
QA +1, doc change only

Merging into master

**Pull request merged**
